[package]
name = "serde_rusqlite"
version = "0.11.2"
description = "Serialize/deserialize rusqlite rows"
keywords = ["serde", "sqlite", "rusqlite", "serialization", "deserialization"]
categories = ["database", "encoding", ]
authors = ["Pro <twisted.fall@gmail.com>"]
license = "LGPL-3.0"
documentation = "https://docs.rs/serde_rusqlite"
repository = "https://github.com/twistedfall/serde_rusqlite"

[dependencies]
error-chain = "0.11"
rusqlite = "0.12"
serde = "1.0"

[dev-dependencies]
matches = "0.1"
serde_bytes = "0.10"
serde_derive = "1.0"
